// #include "exceptions.h"

// MyExeption(const QString& message): std::runtime_error(message.toStdString()), Expmessage(message)
// {}

// QString message() const
// {
//     return Expmessage;
// }

// PhoneException(): MyExeption(QString("invalid phone"))
// {}

// EmailException(): MyExeption(QString("invalid email"))
// {}

// CharactersException(): MyExeption(QString("invalid character"))
// {}

// UsernameException(): MyExeption(QString("This username already exists.")
// {}

